version: '3'
services:

  # Define our service (container) for ROS Master Node
  rover_host:
    container_name: rover_host
    hostname: rover_host
    # Define where Docker Composde should get the image from
    build:
      dockerfile: ./Dockerfile
      target: rover_host
    
    stdin_open: true        # docker run -i
    tty: true               # docker run -t

    # Set enviornment variables
    environment:
      - "ROS_IP=192.0.1.3"        # The IP address of the ROS Host Node
      - "ROS_MASTER_URI=http://192.0.1.3:11311"  # The IP address of the ROS Master Node

    # Attach the network card to the container
    networks:
      rosnet:
        ipv4_address: 192.0.1.3

    #The startup command for this service, run the entrypoint script then run roscore command
    #command: roslaunch ...

    volumes:
      - type: bind
        source: ./..
        target: /home/udmrt/precision1

      # Mac Device Pass Through for Arduino Mega (Motors)
      - type: bind
        source: /dev/cu.usbmodem14101
        target: /dev/ttyUSB3

    #devices:
      #- /dev/ttyUSB0:/dev/ttyUSB0           # Camera
      #- /dev/ttyUSB1:/dev/ttyUSB1           # Main Comms
      #- /dev/ttyUSB2:/dev/ttyUSB2           # Camera Comms
      #- /dev/cu.usbmodem14101:/dev/ttyUSB3   # Arduino Mega Address (Motors)


# Virtual Network card for systems
networks:
  rosnet:
    driver: bridge
    ipam:
     config:
       - subnet: 192.0.1.0/24
         gateway: 192.0.1.1